### ISSUE TITLE
Enum with One Value

### ISSUE THREAD

**Issue by ZouhaierSebri** [bbottema/lorem-ipsum-objects#19] opened 2020-10-08 10:41 UTC
When i Have an Enum with One value I got this error

```
ERROR org.bbottema.loremipsumobjects.typefactories.ClassBasedFactory - error logged:
java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:310)
```

Yes There is always a solution by using ClassBindings for my specific enum like

```java
result.bind(SingleTypeEnum.class, new FixedInstanceFactory<>(SingleTypeEnum.TYPE1));
```

**Comment by bbottema** [comment] 2022-07-14 05:01
Closed as duplicate of #20 (let's keep the discussion there).

**Closed as completed by bbottema** 2022-07-14 05:01 UTC
Labels: duplicate
